### ISSUE TITLE
Env example

### ISSUE THREAD

**Issue by AugustoPinheiro** [SUASecLab/workadventure-admin#1]
Hello!

Great project! You have a .env example and a tutorial to run this?

**Comment by ngc4622** [comment]
Hello,

Thank you for opening the issue. I added an .env template and a docker-compose file (for single domain usage)  for setting up the containers to the repo.
You can use the env template as replacement for WorkAdventure's env file, we only add some variables there.
Most of the variables are self-explainatory. The ADMIN_API_URL variable however, does not point to a domain publicly available, here the admin endpoint for the WorkAdventure back and pusher components is defined. Setting it to something like `http://admin` is sufficient.
The admin web component is routed to `$DOMAIN/admin/`, here you can create login URLs and maps.
Currently, it is only possible to create one administrator, the first username and password entered into the input mask will be used as credentials for the admin user.
The map syntax is the same as registered WorkAdventure maps, in the form of `/@/[organization]/[world]/[map], the limitation in our reimplementation is that organization is always set to `org` and world is set to the `DOMAIN` variable specified in the .env file. Also make sure that the `START_ROOM_URL` is set accordingly.

I hope this helps you, in case there are uncertainties or issues do not hesitate to ask.

Yours,
Tobias

**Comment by AugustoPinheiro** [comment]
How I get theses variables?

# Admin API
ADMIN_API_URL=
ADMIN_API_TOKEN=
ADMIN_API_SALT=
ADMIN_SOCKETS_TOKEN=

**Comment by ngc4622** [comment]
Hello,

See below: 

> ADMIN_API_URL= 

Here, the nginx server hosting the admin websites has to be referenced. This can be either a public URL or the URL of the docker container. If you use the docker compose file provided in the repository, you have to set ADMIN_API_URL to `http://admin` (name of the docker container).

> ADMIN_API_TOKEN= 

This is the token (actually a static password) used internally for authenticating on the administration server. On a fully self-hosted version of WorkAdventure, you can decide which token you use. I would recommend a random 20 character sequence.

> ADMIN_API_SALT= 

This is a salt, providing additional security when hashing the password for the webinterface user. Here you can also use a random character sequence.

> ADMIN_SOCKETS_TOKEN=

Here, the same applies here as for `ADMIN_API_TOKEN`. The only difference is that `ADMIN_API_TOKEN` is used for HTTP requests and `ADMIN_SOCKETS_TOKEN` is used for websockets. Here you can use a random character sequence, too.


Yours,
Tobias

**Comment by ttefke** [comment]
Closed due to inactivity
