### ISSUE TITLE
Help for setup

### ISSUE THREAD

**Issue by Jahe0010** [SUASecLab/workadventure-admin#2]
Hey,

We are from the HSKL and setting up a workadventure environment for our university. 

We have been looking for an admin api and found your repository during our research. 

Somehow data from our running workadventure instance isnt loaded into the database (user connection etc.) 

The requests doesnt throw any errors. 

Can you help us? 

Kind regards

**Comment by Jahe0010** [comment]
the .env variables are set. also i have a user that can log in and log out. 

We dont see any errors in your containers but in the pusher we get a tls certificate error. 

To avoid traefik problems we threw them into the same network. 

Kind regards

**Comment by ngc4622** [comment]
Hi,

Certificate errors will cause the request to fail, as requests to sites with invalid certificates are rejected automatically. So I think there is an issue with the TLS setup. Maybe the error in the pusher components gives you a hint.

If you placed the all containers within the same network, you can also use the hostname of the admin container for the Admin URL, like `ADMIN_API_URL=http://admin`, if `admin` is the name of the nginx container hosting the sites. As the data does not leave the network when using this, TLS is not strictly necessary there. This should work, if you do not redirect to TLS automatically, like in the setup described in https://github.com/SUASecLab/workadventure-admin/blob/main/containers/nginx/default.conf.template

Yours,
Tobias

**Comment by Jahe0010** [comment]
Hi, 

Thanks i forgot about the container name possibility. 

Now we get the following error in the pusher log, maybe you have an idea about that? 
ERROR: Request failed with status code 404 for URL: http://<ContainerID>/admin/api/map

we have the maps placed on our local file system

Where do we hand them the path to find the maps?

when i first started the server i wasnt ask about a map configuration

But we normaly have defined maps
kind regards

**Comment by ngc4622** [comment]
Hi,

This looks like the files are not accessible for the web server. Could it be possible that the volume containing the PHP files are not mounted correctly into the containers? Because of the usage of PHP, also ensure that the paths for the PHP files are the same in the nginx and the PHP containers. It could also be a permission problem, meaning the container sees the files, but nginx or PHP is not allowed to access them. Therefore, I would also recommend to check the permissions.

Concerning the maps, they have to be hosted on a webserver. You can either use the map container provided by WA or set up your own server and host them there (remember to add CORS headers if necessary). In the map part of the admin services, you have to provide a path to the map JSON file and the name the map should have.

I hope, this helps you.

Yours,
Tobias

**Comment by Jahe0010** [comment]
it searchs inside the ngnix container for the map but the map is hosted on an other server and made accessible through an apache

**Comment by ngc4622** [comment]
Hi,

Different servers for the maps and admin services are not a problem, as these services run independently. Are the admin services files present in both the nginx and the PHP container? Are there any permission errors? Is there any output in the logs of the PHP and nginx container, which could indicate an error when accessing the page? Usually, 404 errors are logged by nginx, so you shold be able to see error messages in the logs.

Regarding the map files, you should also be able to see error messages if accessing them fails.

Yours,
Tobias

**Comment by Jahe0010** [comment]
Hi,

What we see in the logs of the nginx is following: 
/var/www/html/admin/api/map" failed (2: No such file or directory)

If we connect into the container and look it up the file is there

Kind regards

**Comment by Jahe0010** [comment]
okay our admin api sends an response now but the pusher says we get "undefined" as a response from the ngnix but if we look into the logs it returns a 200 ok

**Comment by ngc4622** [comment]
Hi,

Do you rewrite the routes correctly, as shown in https://github.com/SUASecLab/workadventure-admin/blob/1e646a70858084e4948457a1c013478277e52788/containers/nginx/default.conf.template#L18 ? This could explain the error in your message above. But status 200 seems fine now.
Do you get errors in the PHP container? Maybe there is a database connection issue or some other problem which causes the failure of the request.

Yours,
Tobias

**Comment by Jahe0010** [comment]
nope it returns 200 too. 

theres no error except in the pusher: 

ERROR: Invalid answer received from the admin for the /api/map endpoint. Received: {"policy_type":1,"mapUrl":"<url>","tags":[],"textures":[]}undefined
Error: Invalid answer received from the admin for the /api/map endpoint. Received: {"policy_type":1,"mapUrl":"<url>","tags":[],"textures":[]}
    at AdminApi.fetchMapDetails (/usr/src/dist/src/Services/AdminApi.js:67:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /usr/src/dist/src/Controller/MapController.js:162:40
ERROR: Invalid answer received from the admin for the /api/map endpoint. Received: " "undefined
Error: Invalid answer received from the admin for the /api/map endpoint. Received: " "
    at AdminApi.fetchMapDetails (/usr/src/dist/src/Services/AdminApi.js:67:19)

**Comment by ngc4622** [comment]
Hi,

This looks like the connection to the map file is missing. As you can see in your error log, the `mapUrl` parameter is empty. In order to being able to join the map, the link to the map JSON file must be sent here. I guess, there either is a problem when fetching the data from the database or no link to a map file was entered when setting up the map in the web interface (then the `Map File URL` column in the enumeration of existing rooms is empty) .

Yours,
Tobias

**Comment by Jahe0010** [comment]
no it wasnt empty the comment just disabled my closing and opening > <

**Comment by Jahe0010** [comment]
the url was valid and when i put it into the browser and send a get request i got the json as a response

**Comment by ngc4622** [comment]
Hi,

Can you please let me know which exact version of WorkAdventure you are using?

Yours,
Tobias

**Comment by Jahe0010** [comment]
Based on the Changelog 1.5

**Comment by ngc4622** [comment]
Hi,

Thank you, we use 1.5.6. Could it be possible that the URL contains characters which are not encoded/decoded correctly? Do you get any other logs which could help in tracing the error?

Yours,
Tobias

**Comment by ttefke** [comment]
Closed due to inactivity
