### ISSUE TITLE
composer container exited with code 0

### ISSUE THREAD

**Issue by jaayb** [SUASecLab/workadventure-admin#4]
Trying to get this up and running however the composer container always ends with exit code of 0.  Not much to see in terms of logs.  shows that it removes the files and copies the new ones but that's about it.  Any thoughts on resolving this?

**Comment by ttefke** [comment]
Hi,

Composer is only used to install some dependencies at its start. After these operations finished, Composer can stop. If I understand you correctly, everything works as specified.

**Comment by jaayb** [comment]
The other containers are running but i cannot browse to the /admin url. I get a gateway timeout response from traefik.

**Comment by ttefke** [comment]
Hi,

do you have more information you can provide? This error can have multiple causes, e.g.:

- the webserver stopped
- the container is not properly configured for traefik

If you do not see anything in the logs, is there something else you can provide? For instance the configuration file of the according webserver and traefik?

**Comment by ttefke** [comment]
Closed due to inactivity
